In [6]:
import os
os.listdir()

['.ipynb_checkpoints',
 'bank_churn_clean.csv',
 'bank_churn_model.ipynb',
 'bank_churn_scored.csv']

In [8]:
import pandas as pd

df = pd.read_csv("bank_churn_clean.csv")
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,NB_Classifier_Score,NB_Attrition_Score
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [1]:
!pip install sqlalchemy pymysql scikit-learn

Requirement already satisfied: sqlalchemy in c:\users\lenovo\anaconda3\lib\site-packages (2.0.30)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/45.3 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.3 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.3 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.3 kB 108.9 kB/s eta 0:00:01
   ------------------------------------ --- 41.0/45.3 kB 195.7 kB/s eta 0:00:01
   ---------------------------------------- 45.3/45.3 kB 171.9 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [2]:
from sqlalchemy import create_engine
import pandas as pd

# Create engine (replace password)
engine = create_engine("mysql+pymysql://root:Ritu0908@localhost/banking_churn")

# Load data from view
df = pd.read_sql("SELECT * FROM churn_model_view", engine)

df.head()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,churn_flag
0,768805383,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691,777,1144,42,0.061,0
1,818770008,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256,864,1291,33,0.105,0
2,713982108,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418,0,1887,20,0.000,0
3,769911858,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313,2517,1171,20,0.760,0
4,709106358,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716,0,816,28,0.000,0

In [3]:
df.shape
df["churn_flag"].value_counts()

churn_flag
0    8500
1    1627
Name: count, dtype: int64

In [4]:
# Remove ID
X = df.drop(columns=["CLIENTNUM", "churn_flag"])

# Target
y = df["churn_flag"]

# Convert categorical variables
X = pd.get_dummies(X, drop_first=True)

X.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,...,Marital_Status_Single,Marital_Status_Unknown,Income_Category_$40K - $60K,Income_Category_$60K - $80K,Income_Category_$80K - $120K,Income_Category_Less than $40K,Income_Category_Unknown,Card_Category_Gold,Card_Category_Platinum,Card_Category_Silver
0,45,3,39,5,1,3,12691,777,1144,42,...,False,False,False,True,False,False,False,False,False,False
1,49,5,44,6,1,2,8256,864,1291,33,...,True,False,False,False,False,True,False,False,False,False
2,51,3,36,4,1,0,3418,0,1887,20,...,False,False,False,False,True,False,False,False,False,False
3,40,4,34,3,4,1,3313,2517,1171,20,...,False,True,False,False,False,True,False,False,False,False
4,40,3,21,5,1,0,4716,0,816,28,...,False,False,False,True,False,False,False,False,False,False

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
model = LogisticRegression(max_iter=2000, class_weight='balanced')
model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=2000)

In [11]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8272458045409674
              precision    recall  f1-score   support

           0       0.96      0.83      0.89      1699
           1       0.48      0.83      0.61       327

    accuracy                           0.83      2026
   macro avg       0.72      0.83      0.75      2026
weighted avg       0.88      0.83      0.84      2026

In [12]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test_scaled)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob))

ROC-AUC: 0.9043834023611659

In [13]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

feature_importance["Absolute_Value"] = abs(feature_importance["Coefficient"])

feature_importance = feature_importance.sort_values(by="Absolute_Value", ascending=False)

feature_importance.head(10)

                           Feature  Coefficient  Absolute_Value
9                   Total_Trans_Ct    -3.105184        3.105184
8                  Total_Trans_Amt     1.706737        1.706737
7              Total_Revolving_Bal    -0.610441        0.610441
5            Contacts_Count_12_mon     0.589710        0.589710
3         Total_Relationship_Count    -0.583823        0.583823
4           Months_Inactive_12_mon     0.549845        0.549845
11                        Gender_M    -0.477083        0.477083
18          Marital_Status_Married    -0.307832        0.307832
24  Income_Category_Less than $40K    -0.281497        0.281497
21     Income_Category_$40K - $60K    -0.268505        0.268505

In [15]:
df["churn_probability"] = model.predict_proba(scaler.transform(X))[:,1]

df[["CLIENTNUM", "churn_probability"]].head()

   CLIENTNUM  churn_probability
0  768805383           0.220885
1  818770008           0.645056
2  713982108           0.845908
3  769911858           0.938686
4  709106358           0.427324

In [16]:
X = df.drop("churn_flag", axis=1)

In [17]:
import joblib

joblib.dump(model, "logistic_churn_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [9]:
df = pd.read_csv("bank_churn_scored.csv")

In [10]:
df.head()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Ct,Avg_Utilization_Ratio,churn_flag,churn_probability
0,768805383,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691,777,1144,42,0.061,0,0.220885
1,818770008,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256,864,1291,33,0.105,0,0.645056
2,713982108,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418,0,1887,20,0.000,0,0.845908
3,769911858,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313,2517,1171,20,0.760,0,0.938686
4,709106358,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716,0,816,28,0.000,0,0.427324